name: web-Automation QA-IN

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types: [automation]

jobs:
  test:
    timeout-minutes: 45
    runs-on: macos-latest

    steps:
      - run: npm cache clean --force
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"
      - run: npm ci
      - run: npx playwright install
      - name: Test on QA-IN
        run: npm run qa-in

      - name: Push test result
        if: always()
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'playwright-report'
          destination-github-username: '100mslive'
          destination-repository-name: 'automation-reports'
          target-directory: 'web'
          user-name: 'github-actions[bot]'
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: qa-in

      - name: Send custom test result
        if: always()
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "Web-Automation build result QA-IN: ${{ job.status }}\n https://web-automation-git-qa-in-100mslive.vercel.app/",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Web-Automation build result QA-IN: ${{ job.status }}\n https://web-automation-git-qa-in-100mslive.vercel.app/"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
